### PR TITLE
README.md updated

### LINKED ISSUE #5: Contributors
Backend Needs a list of people who contributed during labs 26

### PR DESCRIPTION
**Pull request by AlexJoeb**
# Description

Customized the README to include contributors and more personal information about the project. Added a reservation model for getting all reservations with room data attached - this will be used later on for seating/reservation logic.

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Change Status

- [X] Complete, tested, ready to review and merge
- [ ] Complete, but not tested (may need new tests)
- [ ] Incomplete/work-in-progress, PR is for discussion/feedback

# Has This Been Tested?

- [X] Yes
- - [X] What was tested?
- - I used StackEdit Markdown Visualizer to preview what the README will look like.
- [ ] No

# Checklist

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] My code has been reviewed and commented by at least two peers
- [x] I have commented on my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] There are no merge conflicts

### CODE REVIEW

**Review by DrakeAlia — DISMISSED** [review]

**Comment by Carrillo9Ana** [comment]
looks good

**Comment by Carrillo9Ana** [comment]
you might want to add the link to the SwaggerUI API

**Review by Gregory-Hawman — DISMISSED** [review]

**Review by Carrillo9Ana — APPROVED** [review]
very cool!

**Review by DrakeAlia — APPROVED** [review]
The reservation model looks good

**Pull request merged**
